# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DemoData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DemoData.proto',
  package='DemoData',
  serialized_pb=_b('\n\x0e\x44\x65moData.proto\x12\x08\x44\x65moData\"\xe6\x01\n\x08\x43onstant\"Q\n\x07\x43ommand\x12\x16\n\x11\x43MD_USER_REGISTER\x10\x80\x02\x12\x15\n\x10\x43MD_MESSAGE_SEND\x10\x81\x04\x12\x17\n\x12\x43MD_MESSAGE_NOTIFY\x10\x82\x04\"\x86\x01\n\x06Result\x12\x0b\n\x07SUCCESS\x10\x00\x12\x10\n\x0c\x45RROR_PARAMS\x10\x01\x12\x10\n\x0c\x45RROR_SERVER\x10\x02\x12\x18\n\x14\x45RROR_USERNAME_EXIST\x10\x03\x12\x1c\n\x18\x45RROR_USERNAME_NOT_EXIST\x10\x04\x12\x13\n\x0f\x45RROR_FORBIDDEN\x10\x05\"/\n\x0bMessageInfo\x12\x0f\n\x07\x66rom_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"_\n\x0cPacketHeader\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0f\n\x07version\x18\x02 \x01(\r\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\r\x12\x0e\n\x06result\x18\x04 \x01(\r\x12\x11\n\ttimestamp\x18\x05 \x01(\r\"\'\n\x13UserRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"M\n\x12MessageSendRequest\x12\x0f\n\x07targets\x18\x01 \x03(\t\x12&\n\x07message\x18\x02 \x01(\x0b\x32\x15.DemoData.MessageInfo\">\n\x14MessageNotifyRequest\x12&\n\x07message\x18\x01 \x01(\x0b\x32\x15.DemoData.MessageInfo')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CONSTANT_COMMAND = _descriptor.EnumDescriptor(
  name='Command',
  full_name='DemoData.Constant.Command',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CMD_USER_REGISTER', index=0, number=256,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CMD_MESSAGE_SEND', index=1, number=513,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CMD_MESSAGE_NOTIFY', index=2, number=514,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=41,
  serialized_end=122,
)
_sym_db.RegisterEnumDescriptor(_CONSTANT_COMMAND)

_CONSTANT_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='DemoData.Constant.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_PARAMS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_SERVER', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_USERNAME_EXIST', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_USERNAME_NOT_EXIST', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_FORBIDDEN', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=125,
  serialized_end=259,
)
_sym_db.RegisterEnumDescriptor(_CONSTANT_RESULT)


_CONSTANT = _descriptor.Descriptor(
  name='Constant',
  full_name='DemoData.Constant',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONSTANT_COMMAND,
    _CONSTANT_RESULT,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=259,
)


_MESSAGEINFO = _descriptor.Descriptor(
  name='MessageInfo',
  full_name='DemoData.MessageInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from_id', full_name='DemoData.MessageInfo.from_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='DemoData.MessageInfo.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=308,
)


_PACKETHEADER = _descriptor.Descriptor(
  name='PacketHeader',
  full_name='DemoData.PacketHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DemoData.PacketHeader.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='DemoData.PacketHeader.version', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='command', full_name='DemoData.PacketHeader.command', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='DemoData.PacketHeader.result', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='DemoData.PacketHeader.timestamp', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=405,
)


_USERREGISTERREQUEST = _descriptor.Descriptor(
  name='UserRegisterRequest',
  full_name='DemoData.UserRegisterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='DemoData.UserRegisterRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=446,
)


_MESSAGESENDREQUEST = _descriptor.Descriptor(
  name='MessageSendRequest',
  full_name='DemoData.MessageSendRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='targets', full_name='DemoData.MessageSendRequest.targets', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='DemoData.MessageSendRequest.message', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=448,
  serialized_end=525,
)


_MESSAGENOTIFYREQUEST = _descriptor.Descriptor(
  name='MessageNotifyRequest',
  full_name='DemoData.MessageNotifyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='DemoData.MessageNotifyRequest.message', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=527,
  serialized_end=589,
)

_CONSTANT_COMMAND.containing_type = _CONSTANT
_CONSTANT_RESULT.containing_type = _CONSTANT
_MESSAGESENDREQUEST.fields_by_name['message'].message_type = _MESSAGEINFO
_MESSAGENOTIFYREQUEST.fields_by_name['message'].message_type = _MESSAGEINFO
DESCRIPTOR.message_types_by_name['Constant'] = _CONSTANT
DESCRIPTOR.message_types_by_name['MessageInfo'] = _MESSAGEINFO
DESCRIPTOR.message_types_by_name['PacketHeader'] = _PACKETHEADER
DESCRIPTOR.message_types_by_name['UserRegisterRequest'] = _USERREGISTERREQUEST
DESCRIPTOR.message_types_by_name['MessageSendRequest'] = _MESSAGESENDREQUEST
DESCRIPTOR.message_types_by_name['MessageNotifyRequest'] = _MESSAGENOTIFYREQUEST

Constant = _reflection.GeneratedProtocolMessageType('Constant', (_message.Message,), dict(
  DESCRIPTOR = _CONSTANT,
  __module__ = 'DemoData_pb2'
  # @@protoc_insertion_point(class_scope:DemoData.Constant)
  ))
_sym_db.RegisterMessage(Constant)

MessageInfo = _reflection.GeneratedProtocolMessageType('MessageInfo', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGEINFO,
  __module__ = 'DemoData_pb2'
  # @@protoc_insertion_point(class_scope:DemoData.MessageInfo)
  ))
_sym_db.RegisterMessage(MessageInfo)

PacketHeader = _reflection.GeneratedProtocolMessageType('PacketHeader', (_message.Message,), dict(
  DESCRIPTOR = _PACKETHEADER,
  __module__ = 'DemoData_pb2'
  # @@protoc_insertion_point(class_scope:DemoData.PacketHeader)
  ))
_sym_db.RegisterMessage(PacketHeader)

UserRegisterRequest = _reflection.GeneratedProtocolMessageType('UserRegisterRequest', (_message.Message,), dict(
  DESCRIPTOR = _USERREGISTERREQUEST,
  __module__ = 'DemoData_pb2'
  # @@protoc_insertion_point(class_scope:DemoData.UserRegisterRequest)
  ))
_sym_db.RegisterMessage(UserRegisterRequest)

MessageSendRequest = _reflection.GeneratedProtocolMessageType('MessageSendRequest', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGESENDREQUEST,
  __module__ = 'DemoData_pb2'
  # @@protoc_insertion_point(class_scope:DemoData.MessageSendRequest)
  ))
_sym_db.RegisterMessage(MessageSendRequest)

MessageNotifyRequest = _reflection.GeneratedProtocolMessageType('MessageNotifyRequest', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGENOTIFYREQUEST,
  __module__ = 'DemoData_pb2'
  # @@protoc_insertion_point(class_scope:DemoData.MessageNotifyRequest)
  ))
_sym_db.RegisterMessage(MessageNotifyRequest)


# @@protoc_insertion_point(module_scope)
